const oottData = [
    {
        id: 1,
        img: require('/public/oottImg/1.png'),
        tag: "簡約 #美式 #運動",
        date: "2023 / 3 / 7",
        authorphoto:require("@/assets/img/oott_01.png"),
        author: "Jeffery",
        link: "/oott_info",
    },
    {
        id: 2,
        img: require('@/assets/img/oott_02.png'),
        tag: "日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 6,
        img: require('@/assets/img/oott_06.png'),
        tag: "簡約 #休閒 #氣質",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-2_member.png"),
        author: "Susan",
        link: "/oott_info",
    },
    {
        id: 41,
        img: require('@/assets/img/oott_41.png'),
        tag: "簡約 #運動 #休閒",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-3_member.png"),
        author: "Max",
        link: "/oott_info",
    },
   
    {
        id: 3,
        img: require('@/assets/img/oott_03.png'),
        tag: "復古 #性感",
        date: "2023 / 07 / 12",
        authorphoto:require("@/assets/img/oott_03.png"),
        author: "DazzleQueen",
        link: "/oott_info",
    },
    {
        id: 5,
        img: require('@/assets/img/oott_05.png'),
        tag: "休閒",
        date: "2022 / 08 / 31",
        authorphoto:require("@/assets/img/oott_13.png"),
        author: "DuckLord",
        link: "/oott_info",
    },
    {
        id: 10,
        img: require('@/assets/img/oott_10.png'),
        tag: "休閒 #美式",
        date: "2022 / 06 / 24",
        authorphoto:require("@/assets/img/oott_11.png"),
        author: "Kay",
        link: "/oott_info",
    },
    {
        id: 11,
        img: require('@/assets/img/oott_11.png'),
        tag: "休閒 #美式",
        date: "2022 / 09 / 06",
        authorphoto:require("@/assets/img/oott_11.png"),
        author: "Kay",
        link: "/oott_info",
    },
    {
        id: 12,
        img: require('@/assets/img/oott_12.png'),
        tag: "可愛 #日系 #運動",
        date: "2022 / 01 / 08",
        authorphoto:require("@/assets/img/oott_kid.png"),
        author: "Kid",
        link: "/oott_info",
    },
    {
        id: 40,
        img: require('@/assets/img/oott_40.png'),
        tag: "韓系 #休閒",
        date: "2022 / 06/ 12",
        authorphoto:require("@/assets/img/oott_kid.png"),
        author: "Kid",
        link: "/oott_info",
    },
    {
        id: 18,
        img: require('@/assets/img/oott_18.png'),
        tag: "休閒",
        date: "2022 / 11 / 27",
        authorphoto:require("@/assets/img/oott_13.png"),
        author: "DuckLord",
        link: "/oott_info",
    },
    {
        id: 14,
        img: require('@/assets/img/oott_14.png'),
        tag: "簡約 #休閒",
        date: "2022 / 07 / 29",
        authorphoto:require("@/assets/img/oott_11.png"),
        author: "Kay",
        link: "/oott_info",
    },
    
]
export default oottData;