const oottData = [
    {
        id: 1,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 2,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 3,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 4,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 5,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 6,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 7,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 8,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 9,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 10,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 11,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
    {
        id: 12,
        img: require('@/assets/img/oott_card_example 2.png'),
        tag: "#日系 #休閒 #風景",
        date: "2022 / 12 / 12",
        authorphoto:require("@/assets/img/layout/plan_result_oott-1_member.png"),
        author: "Ailson",
        link: "/oott_info",
    },
]
export default oottData;