const ticketData = [
    {
        id: 1,
        Name: "斑比山丘門票A",
        img: require("@/assets/img/ticketExample.png"),
        location: "宜蘭",
        tag: "#親子#情侶#農場",
        ticket_details:
            "大受歡迎的親子景點，園區內有多種動物，可以與梅花鹿、水豚、羊咩咩來場親密的互動。美美子咖啡廳的冰淇淋十分美味，推薦給所有人到店購買品嚐。",
        ticket_addr: "宜蘭縣冬山鄉下湖路285號",
        ticket_addr_link: "https://goo.gl/maps/bT2uJusZ3vYEofDF7",
        price_adultO: 100,
        price_adultF: 50,
        price_exO: 300,
        price_exF: 150,
        discount: "5折",
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        singlecard_link: "/ticket_info",
    },
    {
        id: 2,
        Name: "斑比山丘門票B",
        img: require("@/assets/img/ticketExample.png"),
        location: "宜蘭",
        tag: "#親子#情侶#農場",
        ticket_details:
            "大受歡迎的親子景點，園區內有多種動物，可以與梅花鹿、水豚、羊咩咩來場親密的互動。美美子咖啡廳的冰淇淋十分美味，推薦給所有人到店購買品嚐。",
        ticket_addr: "宜蘭縣冬山鄉下湖路285號",
        ticket_addr_link: "https://goo.gl/maps/bT2uJusZ3vYEofDF7",
        price_adultO: 140,
        price_adultF: 70,
        price_exO: 30,
        price_exF: 15,
        discount: "5折",
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        singlecard_link: "/ticket_info",
    },
    {
        id: 3,
        Name: "斑比山丘門票C",
        img: require("@/assets/img/ticketExample.png"),
        location: "宜蘭",
        tag: "#親子#情侶#農場",
        ticket_details:
            "大受歡迎的親子景點，園區內有多種動物，可以與梅花鹿、水豚、羊咩咩來場親密的互動。美美子咖啡廳的冰淇淋十分美味，推薦給所有人到店購買品嚐。",
        ticket_addr: "宜蘭縣冬山鄉下湖路285號",
        ticket_addr_link: "https://goo.gl/maps/bT2uJusZ3vYEofDF7",
        price_adultO: 240,
        price_adultF: 120,
        price_exO: 300,
        price_exF: 150,
        discount: "5折",
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        singlecard_link: "/ticket_info",
    },
    {
        id: 4,
        Name: "斑比山丘門票D",
        img: require("@/assets/img/ticketExample.png"),
        location: "宜蘭",
        tag: "#親子#情侶#農場",
        ticket_details:
            "大受歡迎的親子景點，園區內有多種動物，可以與梅花鹿、水豚、羊咩咩來場親密的互動。美美子咖啡廳的冰淇淋十分美味，推薦給所有人到店購買品嚐。",
        ticket_addr: "宜蘭縣冬山鄉下湖路285號",
        ticket_addr_link: "https://goo.gl/maps/bT2uJusZ3vYEofDF7",
        price_adultO: 460,
        price_adultF: 230,
        price_exO: 300,
        price_exF: 150,
        discount: "5折",
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        singlecard_link: "/ticket_info",
    },
    {
        id: 5,
        Name: "斑比山丘門票E",
        img: require("@/assets/img/ticketExample.png"),
        location: "宜蘭",
        tag: "#親子#情侶#農場",
        ticket_details:
            "大受歡迎的親子景點，園區內有多種動物，可以與梅花鹿、水豚、羊咩咩來場親密的互動。美美子咖啡廳的冰淇淋十分美味，推薦給所有人到店購買品嚐。",
        ticket_addr: "宜蘭縣冬山鄉下湖路285號",
        ticket_addr_link: "https://goo.gl/maps/bT2uJusZ3vYEofDF7",
        price_adultO: "",
        price_adultF: 300,
        price_exO: "",
        price_exF: 150,
        discount: "",
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        singlecard_link: "/ticket_info",
    },
    {
        id: 6,
        Name: "斑比山丘門票F",
        img: require("@/assets/img/ticketExample.png"),
        location: "宜蘭",
        tag: "#親子#情侶#農場",
        ticket_details:
            "大受歡迎的親子景點，園區內有多種動物，可以與梅花鹿、水豚、羊咩咩來場親密的互動。美美子咖啡廳的冰淇淋十分美味，推薦給所有人到店購買品嚐。",
        ticket_addr: "宜蘭縣冬山鄉下湖路285號",
        ticket_addr_link: "https://goo.gl/maps/bT2uJusZ3vYEofDF7",
        price_adultO: 100,
        price_adultF: 50,
        price_exO: 30,
        price_exF: 15,
        discount: "5折",
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        singlecard_link: "/ticket_info",
    },
    {
        id: 7,
        Name: "斑比山丘門票G",
        img: require("@/assets/img/ticketExample.png"),
        location: "宜蘭",
        tag: "#親子#情侶#農場",
        ticket_details:
            "大受歡迎的親子景點，園區內有多種動物，可以與梅花鹿、水豚、羊咩咩來場親密的互動。美美子咖啡廳的冰淇淋十分美味，推薦給所有人到店購買品嚐。",
        ticket_addr: "宜蘭縣冬山鄉下湖路285號",
        ticket_addr_link: "https://goo.gl/maps/bT2uJusZ3vYEofDF7",
        price_adultO: 400,
        price_adultF: 200,
        price_exO: 300,
        price_exF: 150,
        discount: "5折",
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        singlecard_link: "/ticket_info",
    },
    {
        id: 8,
        Name: "斑比山丘門票H",
        img: require("@/assets/img/ticketExample.png"),
        location: "宜蘭",
        tag: "#親子#情侶#農場",
        ticket_details:
            "大受歡迎的親子景點，園區內有多種動物，可以與梅花鹿、水豚、羊咩咩來場親密的互動。美美子咖啡廳的冰淇淋十分美味，推薦給所有人到店購買品嚐。",
        ticket_addr: "宜蘭縣冬山鄉下湖路285號",
        ticket_addr_link: "https://goo.gl/maps/bT2uJusZ3vYEofDF7",
        price_adultO: "",
        price_adultF: 250,
        price_exO: "",
        price_exF: 150,
        discount: "",
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        singlecard_link: "/ticket_info",
    },
];
export default ticketData;
