const ticketData = [
    {
        id: 1,
        Name: "景點A門票",
        img: require("@/assets/img/ticketExample.png"),
        location: "地點",
        tag: "#標籤",
        ticket_details: "",
        ticket_addr: "",
        price_adultO: "$NT" + 100,
        price_adultF: "$NT" + 50,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 2,
        Name: "景點B門票",
        img: require("@/assets/img/ticketExample.png"),
        location: "地點",
        tag: "#標籤",
        ticket_details: "",
        ticket_addr: "",
        price_adultO: "$NT" + 140,
        price_adultF: "$NT" + 70,
        price_exO: 30,
        price_exF: 15,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 3,
        Name: "景點C門票",
        img: require("@/assets/img/ticketExample.png"),
        location: "地點",
        tag: "#標籤",
        ticket_details: "",
        ticket_addr: "",
        price_adultO: "$NT" + 240,
        price_adultF: "$NT" + 120,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 4,
        Name: "景點D門票",
        img: require("@/assets/img/ticketExample.png"),
        location: "地點",
        tag: "#標籤",
        ticket_details: "",
        ticket_addr: "",
        price_adultO: "$NT" + 460,
        price_adultF: "$NT" + 230,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 5,
        Name: "景點E門票",
        img: require("@/assets/img/ticketExample.png"),
        location: "地點",
        tag: "#標籤",
        ticket_details: "",
        ticket_addr: "",
        price_adultO: "$NT" + 600,
        price_adultF: "$NT" + 300,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 6,
        Name: "景點F門票",
        img: require("@/assets/img/ticketExample.png"),
        location: "地點",
        tag: "#標籤",
        ticket_details: "",
        ticket_addr: "",
        price_adultO: "$NT" + 100,
        price_adultF: "$NT" + 50,
        price_exO: 30,
        price_exF: 15,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 7,
        Name: "景點G門票",
        img: require("@/assets/img/ticketExample.png"),
        location: "地點",
        tag: "#標籤",
        ticket_details: "",
        ticket_addr: "",
        price_adultO: "$NT" + 400,
        price_adultF: "$NT" + 200,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 8,
        Name: "景點H門票",
        img: require("@/assets/img/ticketExample.png"),
        location: "地點",
        tag: "#標籤",
        ticket_details: "",
        ticket_addr: "",
        price_adultO: "$NT" + 500,
        price_adultF: "$NT" + 250,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
];
export default ticketData;
