const ticketData = [
    {
        id: 1,
        Name: "票券A",
        img: "https://picsum.photos/300/200/?random=9",
        tag: "#標籤",
        price_adultO: 100,
        price_adultF: 50,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 2,
        Name: "票券B",
        img: "https://picsum.photos/300/200/?random=10",
        tag: "#標籤",
        price_adultO: 1400,
        price_adultF: 700,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 3,
        Name: "票券C",
        img: "https://picsum.photos/300/200/?random=11",
        tag: "#標籤",
        price_adultO: 2400,
        price_adultF: 1200,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 4,
        Name: "票券D",
        img: "https://picsum.photos/300/200/?random=12",
        tag: "#標籤",
        price_adultO: 4600,
        price_adultF: 2300,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 5,
        Name: "票券E",
        img: "https://picsum.photos/300/200/?random=13",
        tag: "#標籤",
        price_adultO: 600,
        price_adultF: 300,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 6,
        Name: "票券F",
        img: "https://picsum.photos/300/200/?random=14",
        tag: "#標籤",
        price_adultO: 1000,
        price_adultF: 500,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 7,
        Name: "票券G",
        img: "https://picsum.photos/300/200/?random=15",
        tag: "#標籤",
        price_adultO: 400,
        price_adultF: 200,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
    {
        id: 8,
        Name: "票券H",
        img: "https://picsum.photos/300/200/?random=16",
        tag: "#標籤",
        price_adultO: 500,
        price_adultF: 250,
        price_exO: 300,
        price_exF: 150,
        count_adult: 0,
        count_ex: 0,
        subtotal: 0,
        link: "/ticketinfo",
    },
];
export default ticketData;
